version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building project..."
      - echo "<html><body><h1>Hello from CodePipeline Deploy Stage! Test Test2</h1></body></html>" > index.html
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - 'index.html'

